# from <https://github.com/taocpp/PEGTL/blob/master/.travis.yml>

os: linux
dist: xenial
sudo: false

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-4.9
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-5
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-6
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-7
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-8
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.8']
          packages: ['clang-3.8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-3.8
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.9']
          packages: ['clang-3.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-3.9
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-4.0']
          packages: ['clang-4.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-4.0
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
          packages: ['clang-5.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-5.0
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
          packages: ['clang-6.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-6.0
        - GPG_COMPATIBLE=False

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
          packages: ['clang-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-7
        - GPG_COMPATIBLE=False

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-4.9
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-5
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-6
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-7
        - GPG_COMPATIBLE=True

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=g++-8
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.8']
          packages: ['clang-3.8', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-3.8
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-3.9']
          packages: ['clang-3.9', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-3.9
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-4.0']
          packages: ['clang-4.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-4.0
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
          packages: ['clang-5.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-5.0
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
          packages: ['clang-6.0', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-6.0
        - GPG_COMPATIBLE=True

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
          packages: ['clang-7', 'libgmp-dev', 'libbz2-dev', 'zlib1g-dev', 'cmake']
      env:
        - CXX_COMPILER=clang++-7
        - GPG_COMPATIBLE=True

before_script:
  - export CXX=${CXX_COMPILER}
  - export GTEST_COLOR=1
  - export OPENPGP_PATH=/tmp/OpenPGP

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=${OPENPGP_PATH} -DCMAKE_BUILD_TYPE=Debug -DGPG_COMPATIBLE="${GPG_COMPATIBLE}"
  - cmake --build .
  - ctest --verbose

after_success:
  - make install

  # rebuild the cli as a standalone application using the installed files
  - ${CXX} -Wall -std=c++11 -I${OPENPGP_PATH}/include ../cli/main.cpp ../cli/modules/module.cpp -L${OPENPGP_PATH}/lib -lOpenPGP -lgmp -lgmpxx -lbz2 -lz -o OpenPGP
  - export LD_LIBRARY_PATH=${OPENPGP_PATH}/lib:$LD_LIBRARY_PATH
  - ./OpenPGP